### ISSUE TITLE
Issues with Python 3.5

### ISSUE THREAD

**Issue by Arttii** [elastic/elasticsearch-py-async#2]
Hi,

I am trying to run the example from the docs with Python 3.5 and the elasticsearch-py(5.0 I think) from the master branch and it does not seem to be working.

I keep getting:
``AssertionError: yield from wasn't used with future``

Not sure whats the problem. Detailed stack trace.

`Traceback (most recent call last):
  File "/home/arti/workdir/man/services/imp/search/query/test.py", line 12, in <module>
    loop.run_until_complete(print_info())
  File "/opt/anaconda3/envs/imp_search/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/imp_search/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/anaconda3/envs/imp_search/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/arti/workdir/man/services/imp/search/query/test.py", line 8, in print_info
    info = yield from client.info()
  File "/opt/anaconda3/envs/imp_search/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/anaconda3/envs/imp_search/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 219, in info
    _, data = self.transport.perform_request('GET', '/', params=params)
  File "/opt/anaconda3/envs/imp_search/lib/python3.5/asyncio/futures.py", line 359, in __iter__
    assert self.done(), "yield from wasn't used with future"
AssertionError: yield from wasn't used with future
Task was destroyed but it is pending!
task: <Task pending coro=<TCPConnector._create_connection() running at /opt/anaconda3/envs/imp_search/lib/python3.5/site-packages/aiohttp/connector.py:558> cb=[_release_waiter(<Future pendi...sk._wakeup()]>)() at /opt/anaconda3/envs/imp_search/lib/python3.5/asyncio/tasks.py:344]>
Task was destroyed but it is pending!
task: <Task pending coro=<AsyncTransport.main_loop() running at /opt/anaconda3/envs/imp_search/lib/python3.5/site-packages/elasticsearch_async/transport.py:140> wait_for=<Future pending cb=[Task._wakeup()]>>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f208fb83240>
`

**Comment by HonzaKral** [comment]
It looks like you are trying to use this connection with an older version of `elasticsearch-py`. Currently it is only compatible with version from git (`2.x` branch) of `elasticsearch-py`). Sorry for the confusion.

**Comment by Arttii** [comment]
Hi,
I seem to have installed the one from the correct branch to the wrong virtualenv. It seems to work with elasticsearch-5.0.0.dev0. Thanks.
