### ISSUE TITLE
Incompatible with aiohttp>=3.6 

### ISSUE THREAD

**Issue by ibt23sec5** [elastic/elasticsearch-py-async#74]
Hello, 
`elasticsearch_async` is no more compatible with `aiohttp`, since version 3.6 due to [dropping](https://github.com/aio-libs/aiohttp/pull/3580) of explicit parameter `loop`:
```
Traceback (most recent call last):
  ... 
    self.client = elasticsearch_async.AsyncElasticsearch(hosts=es_addresses)
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch_async-6.2.0-py3.7.egg/elasticsearch_async/__init__.py", line 8, in __init__
    super().__init__(hosts, transport_class=transport_class, **kwargs)
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch-7.5.1-py3.7.egg/elasticsearch/client/__init__.py", line 227, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch_async-6.2.0-py3.7.egg/elasticsearch_async/transport.py", line 23, in __init__
    connection_pool_class=connection_pool_class, **kwargs)
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch-7.5.1-py3.7.egg/elasticsearch/transport.py", line 129, in __init__
    self.set_connections(hosts)
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch_async-6.2.0-py3.7.egg/elasticsearch_async/transport.py", line 56, in set_connections
    super().set_connections(hosts)
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch-7.5.1-py3.7.egg/elasticsearch/transport.py", line 179, in set_connections
    connections = list(zip(connections, hosts))
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch-7.5.1-py3.7.egg/elasticsearch/transport.py", line 175, in _create_connection
    return self.connection_class(**kwargs)
  File "/home/ibt23sec5/projects/urpp/venv/lib/python3.7/site-packages/elasticsearch_async-6.2.0-py3.7.egg/elasticsearch_async/connection.py", line 73, in __init__
    ssl_context=ssl_context,
TypeError: __init__() got an unexpected keyword argument 'loop'
```

**Comment by sethmlarson** [comment]
This is being tracked here: https://github.com/elastic/elasticsearch-py/issues/1332
See https://github.com/elastic/elasticsearch-py-async/issues/81 for more information.
